export function serializeApplication(application) {
  return {
    id: application._id.toString(),
    sdmsCode: application.sdmsCode,
    firstName: application.firstName,
    lastName: application.lastName,
    fullName: `${application.firstName} ${application.lastName}`.trim(),
    lastLevelMark: application.lastLevelMark,
    tradeOrSection: application.tradeOrSection,
    model: application.model,
    gender: application.gender,
    level: application.level,
    fatherName: application.fatherName,
    motherName: application.motherName,
    phone: application.phone,
    dateOfBirth: application.dateOfBirth,
    studentEmail: application.studentEmail,
    reasonToApply: application.reasonToApply,
    status: application.status,
    adminNotes: application.adminNotes,
    additionalFormRequestedAt: application.additionalFormRequestedAt,
    additionalFormSubmittedAt: application.additionalFormSubmittedAt,
    schoolFeesDetails: application.schoolFeesDetails,
    additionalInformation: application.additionalInformation,
    schoolFeesApprovalFileName: application.schoolFeesApprovalFileName,
    schoolFeesApprovalFileUrl: application.schoolFeesApprovalFileUrl,
    emailLogs: application.emailLogs || [],
    createdAt: application.createdAt,
    updatedAt: application.updatedAt,
  };
}
